Linear Algebra in Python

In [1]:
import numpy as np

In [4]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [6]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [8]:
v_add = v1 + v2
v_sub = v1 - v2
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [10]:
scalar = 2
v_scaled = v1*scalar
print(v_scaled)

[2 4 6]


In [11]:
dot_product = np.dot(v1,v2)
print ( dot_product) # 1*4 + 2*5 + 3*6 = 32

32


In [14]:
magnitude_v1=np.linalg.norm(v1)
print (magnitude_v1) # sqrt(1^2 + 2^2 + 3^2)

3.7416573867739413


In [18]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()

B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [20]:
C = np.array([[1,2,3],[4,5,6]])
matrix_add = A+C
matrix_sub = A-C

print("A+C=\n", matrix_add)
print("A-C\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C
 [[0 0 0]
 [0 0 0]]


In [21]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


Solving Systems of Linear Equations

In [30]:
A = np.array([[2,3],[4,-1]])
b = np.array([5,3])

print(A,'\n')
print(b, '\n')

x = np.linalg.solve(A,b)
print('Solution:\n', x)

[[ 2  3]
 [ 4 -1]] 

[5 3] 

Solution:
 [1. 1.]


Eigen...

In [32]:
A = np.array([[2,1],[1,2]])
e_value, e_vectors = np.linalg.eig(A)
print("eigenvalue: ", e_value)
print("eigenvector: ", e_vectors)

eigenvalue:  [3. 1.]
eigenvector:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Inverse

In [34]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [36]:
identity = np.dot(A,A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Identity Matrix : 1 0 0
                  0 1 0
                  0 0 1